# Phase equilibria including derivatives

In [1]:
from feos import PropertiesAD, ModelAD
import numpy as np

## Vapor pressure

In [2]:
n = 10000000
fit_params = ["m", "sigma", "epsilon_k"]
parameters = np.array([[1.5,3.4,230.,2.3]]*n)
temperature = np.expand_dims(np.linspace(250., 400.0, n),1)
%time PropertiesAD.vapor_pressure(ModelAD.PcSaftNonAssoc, fit_params, parameters, temperature)

CPU times: user 1min 36s, sys: 777 ms, total: 1min 37s
Wall time: 2.26 s


(array([  99933.70173872,   99933.76369505,   99933.82565141, ...,
        4841855.06247647, 4841856.28251754, 4841857.50255883],
       shape=(10000000,)),
 array([[-1.04684676e+05,  1.37290974e+05, -2.94409278e+03],
        [-1.04684730e+05,  1.37291045e+05, -2.94409438e+03],
        [-1.04684784e+05,  1.37291116e+05, -2.94409599e+03],
        ...,
        [-3.06545385e+06,  2.31346293e+06, -8.79512373e+04],
        [-3.06545458e+06,  2.31346323e+06, -8.79512573e+04],
        [-3.06545531e+06,  2.31346353e+06, -8.79512774e+04]],
       shape=(10000000, 3)),
 array([ True,  True,  True, ...,  True,  True,  True], shape=(10000000,)))

## Liquid density

In [3]:
n = 10000000
fit_params = ["m", "sigma", "epsilon_k"]
parameters = np.array([[1.5,3.4,230.,2.3]]*n)
temperature = np.linspace(250., 400.0, n)
pressure = np.array([1e5]*n)
input = np.stack((temperature, pressure),axis=1)
%time PropertiesAD.liquid_density(ModelAD.PcSaftNonAssoc, fit_params, parameters, input)

CPU times: user 1min 23s, sys: 744 ms, total: 1min 24s
Wall time: 2.13 s


(array([22.7191149 , 22.71911436, 22.71911382, ...,  0.03027266,
         0.03027266,  0.03027266], shape=(10000000,)),
 array([[-1.68941171e+01, -2.24206688e+01,  2.73083514e-02],
        [-1.68941167e+01, -2.24206685e+01,  2.73083541e-02],
        [-1.68941164e+01, -2.24206681e+01,  2.73083568e-02],
        ...,
        [ 9.49488124e-05,  9.60641306e-06,  7.80107221e-07],
        [ 9.49487960e-05,  9.60641033e-06,  7.80107128e-07],
        [ 9.49487795e-05,  9.60640761e-06,  7.80107035e-07]],
       shape=(10000000, 3)),
 array([ True,  True,  True, ...,  True,  True,  True], shape=(10000000,)))

## Bubble points

In [4]:
n = 1000000
fit_params = ["k_ij"]
parameters = np.array([[1.5,3.4,230.,2.3,2.3,3.5,245.,1.4,0.01]]*n)
temperature = np.linspace(200., 406.0, n)
molefracs = np.array([.5]*n)
pressure = np.array([1e5]*n)
input = np.stack((temperature, molefracs, pressure),axis=1)
%time PropertiesAD.bubble_point_pressure(ModelAD.PcSaftNonAssoc, fit_params, parameters, input)

CPU times: user 11min 19s, sys: 113 ms, total: 11min 19s
Wall time: 11.1 s


(array([   5142.13808145,    5142.20830389,    5142.27852715, ...,
        3828278.20909898, 3828290.44546341, 3828302.68185363],
       shape=(1000000,)),
 array([[   40721.23744125],
        [   40721.73456205],
        [   40722.23168782],
        ...,
        [10996502.56325178],
        [10996528.1146768 ],
        [10996553.66610128]], shape=(1000000, 1)),
 array([ True,  True,  True, ...,  True,  True,  True], shape=(1000000,)))

## Bubble points with cross-association

In [5]:
n = 100000
fit_params = ["k_ij"]
parameters = np.array([[1.5,3.4,230.,2.3,0.01,1200.,1.0,2.0,2.3,3.5,245.,1.4,0.01,0.005,500.,1.0,1.0]]*n)
temperature = np.linspace(200., 388.0, n)
molefracs = np.array([.5]*n)
pressure = np.array([1e5]*n)
input = np.stack((temperature, molefracs, pressure),axis=1)
%time PropertiesAD.bubble_point_pressure(ModelAD.PcSaftFull, fit_params, parameters, input)

CPU times: user 3min 17s, sys: 8.02 ms, total: 3min 17s
Wall time: 3.18 s


(array([  14214.36303538,   14215.92004937,   14217.47719969, ...,
        2743164.02664754, 2743236.48124057, 2743308.93709014],
       shape=(100000,)),
 array([[  58742.88648703],
        [  58748.51845106],
        [  58754.15082369],
        ...,
        [5046367.67160589],
        [5046476.22016725],
        [5046584.7699692 ]], shape=(100000, 1)),
 array([ True,  True,  True, ...,  True,  True,  True], shape=(100000,)))